server.port=8086
spring.application.name=bff
microservices.security.user=postgres
microservices.security.password=12345

spring.cloud.openfeign.circuitbreaker.enabled=true

resilience4j.circuitbreaker.instances.ms-sucursales.sliding-window-size=10
resilience4j.circuitbreaker.instances.ms-sucursales.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.ms-sucursales.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.ms-sucursales.permitted-number-of-calls-in-half-open-state=3

